### ISSUE TITLE
Latest version is not released

### ISSUE THREAD

**Issue by ulasakdeniz** [frictionlessdata/tableschema-go#100]
# Overview

On Github [Releases](https://github.com/frictionlessdata/tableschema-go/releases/tag/v.1.5.1) page it looks like there is a `v1.5.1` release but it is not on [pkg.go.dev](https://pkg.go.dev/github.com/frictionlessdata/tableschema-go). The last released version is `v1.1.3`.

---

Please preserve this line to notify @danielfireman (lead of this repository)

**Comment by danielfireman** [comment]
Thanks a lot for reporting, @ulasakdeniz!

Somehow the releasing/tagging got messed up. I released a new version and forced pkg.dev update. Now https://pkg.go.dev/github.com/frictionlessdata/tableschema-go@v1.5.2 is appropriately showing up.

**Comment by ulasakdeniz** [comment]
Hi @danielfireman that's great. Thanks a lot!
