### ISSUE TITLE
Add frictionless data field tags to structs

### ISSUE THREAD

**Issue by danielfireman** [frictionlessdata/tableschema-go#15]
This will make more flexible to declare structs to encode/decode table rows.

Example:
```go
type MyRow  struct {
   MyName string `tableheader:name`
}
```

MyName field will be populated with values from the "name" column (header)

For reference:

* https://github.com/frictionlessdata/tableschema-go/blob/master/schema/schema.go#L189
* https://github.com/frictionlessdata/tableschema-go/blob/master/schema/schema.go#L223

**Comment by as27** [comment]
That idea is great. I don't have so much experience with reflection, but I will try.

**Comment by danielfireman** [comment]
Awesome! Implementing [schema.Decode](https://github.com/frictionlessdata/tableschema-go/blob/master/schema/schema.go#L189) and [schema.Encode](https://github.com/frictionlessdata/tableschema-go/blob/master/schema/schema.go#L223) was a lot of fun and learning. I had not had much experience with reflection either :smiley:

**Comment by as27** [comment]
Just send a PR. It was much easier then expected. So Encode() and Decode() are great implemented. Well done.

**Comment by danielfireman** [comment]
> Just send a PR. It was much easier than expected. 

It is great that you could easily implement this feature! Great stuff. Already sent you some suggestions/comments.

> So Encode() and Decode() are great implemented. Well done.

I am flattered :see_no_evil: .. Thanks a lot!

**Comment by danielfireman** [comment]
Super happy to close this issue! This feature greatly improves tableschema-go's usability!
