### ISSUE TITLE
Add Schema header's map

### ISSUE THREAD

**Issue by danielfireman** [frictionlessdata/tableschema-go#16]
This would make CastRow faster (in particular for tables with many fields)

**Comment by danielfireman** [comment]
Created a function and factored out the access GetField. 

One caveat of this is that in CastRow we actually need the index describing the position of the field in the descriptor. So, maybe the map would be: map[string]int, mapping name to position.

**Comment by roll** [comment]
Minor notes that lately in implementations we've started to distinct:
- schema have field names
- data table have headers

**Comment by danielfireman** [comment]
This was actually a (premature) optimization. Let's wait for schema decode/encode and start optimizing it based on actual profiling.
