### ISSUE TITLE
Maps versus strong types

### ISSUE THREAD

**Issue by danielfireman** [frictionlessdata/tableschema-go#3]
The flexibility in schema description seems to play really well in dynamically typed languages like Python or Javascript. For example, let's take a look in the a following code fragment [tableschema-py](https://github.com/frictionlessdata/tableschema-py#example):

```python
def skip_under_30(erows):
    for number, headers, row in erows:
        krow = dict(zip(headers, row))
        if krow['age'] >= 30:
            yield (number, headers, row)
table = Table(SOURCE, **post_cast=[skip_under_30])**
```

The Golang and Java counterparts for the tableschema library could simply translate this code using `map[string]interface{}` and `Map<String, Object>`, respectively. All type checking is gone and development is slower and more error prone, as the code would be full of type conversions (hopefully lots of methods converting back and forth maps to [POJOs](https://en.wikipedia.org/wiki/Plain_old_Java_object)). I have the feeling this is not ideal.

Some research would lead to  APIs like the [Amazon's DynamoDB](http://docs.aws.amazon.com/amazondynamodb/latest/gettingstartedguide/GettingStarted.Java.04.html), which relies on objects like [Item](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/document/Item.html). Even though the Item object is super general, it has methods that return its inner contents using the right type. Important to notice that to access some field from an item is done through a string. So, the developer needs to have extra care to use the same constant when creating, updating (describe) and using the item. I feel this is an improvement when compared to pure general maps, but still not ideal.

Another option would be the [Golang's database/sql Query](https://golang.org/pkg/database/sql/#example_DB_Query). The difference from the above is that type conversion would be done transparently (without need to invoke the right method based on the type). Important to notice that it is fully positional, the order of the query parameter is the exact same order returned by the [Rows.Scan](https://golang.org/pkg/database/sql/#Rows.Scan) method. Depending on your background, you can feel like this improves things a bit. I feel we are exchanging the field name (string constant above) by a field id.

More research and thought led me to remember [Google's protocol buffers](https://developers.google.com/protocol-buffers/) approach (not suggesting to use protocol buffers here): we could generate the code to access the table from the table schema. We could even generate the JSON and CSV serializers.

* _Pros_ : Cleaner, more idiomatic and more performant code
* _Cons_ :
     * The object describing each table row would need to be generated beforehand. 
     * Need to maintain one more piece of software: the code generator
     * Support more languages go through add a new generator

I would argue that these objects need to be shipped in the data package describing them. To the other two cons, it is really a trade off. I am personally in favor of having the tableschema team (and maybe external contributors) creating and maintaining the code generator. I believe that would lead to much cleaner and more performant code reading, processing and extracting useful information from data and this is where the bulk of complexity will (and should be).

---
- Edit: Added database/sql option

**Comment by pwalsh** [comment]
@akariv

**Comment by roll** [comment]
@danielfireman 
I just going to dive into the problem but I could say about your example - things like `post_cast` is an extended level of FrictionlessData implementations (see https://github.com/frictionlessdata/implementations#tableschema). We support it only in Python.

**Comment by akariv** [comment]
@danielfireman why not go the way that the standard `json` implementation is done in Go:
https://blog.golang.org/json-and-go

You can pass an interface with the correct fields, in which case unmarshalling will fill these fields. If you pass an empty interface, a map will be created. That's the best of both worlds.

**Comment by danielfireman** [comment]
Thanks for chiming in, @akariv! Totally agree that is the best of both worlds. @roll, could we close on that? Further comments?

As per request from @roll, let's sumarize with examples from all options so far. We are going to use the following python fragment as guide:

```python
table = tableschema.Table('data.csv', schema='schema.json')
table.headers # ['name', 'age']
records = table.read() # [['John', 55], ['Alex', 25]]
age_sum = 0
for r in records:
  age_sum = age_sum + r[1]
  print 'Name:', r[0], 'Age:', r[1]
print 'Average age:', age_sum/len(records)
```

* map[string]interface{} (equivalent to Map<String, Object> in java)

```go
table, _ := tableschema.Table('data.csv', schema='schema.json')
fmt.Println(table.Headers()) //  ["name", "age"]
records = table.All(context.Background())
ageSum := 0.0
for _, r := range records {
    name := string(r["name"])
    age := int(r["age"])
    ageSum += float(age)
    fmt.Printf("Name: %s Age: %d\n", name, age)
}
fmt.Println("Average age:%f", ageSum/10.0)
```

* Very general objects with accessor methods

```go
// ... Same as above
for _, r := range records {
    name := r["name"].AsString()
    age := r["age"].AsInt()
    ageSum += float(age)
    fmt.Printf("Name: %s Age: %d\n", name, age)
}
// ... Same as above
```

* database/sql like

```go
// ... Same as above
var string name
var age int
for _, r := range records {
    r.Scanf(&name, &age)  // This needs to be in the same order as headars
    ageSum += float(age)
    fmt.Printf("Name: %s Age: %d\n", name, age)
}
// ... Same as above
```

* Code generator

```go
table, _ := tableschema.Table('data.csv', schema='schema.json')
fmt.Println(table.Headers()) //  ["name", "age"]
var records []Record
table.All(context.Background(), &records)
for _, r := range records {
    ageSum += float(r.Age)
    fmt.Printf("Name: %s Age: %d\n", r.Name, r.Age)
}
fmt.Println("Average age:%f", ageSum/10.0)
```

* JSON Like

```go
table, _ := tableschema.Table('data.csv', schema='schema.json')
fmt.Println(table.Headers()) //  ["name", "age"]
var records []struct {
   Name string `header:"name"`
   Age int `header:"age"`
}
table.All(context.Background(), &records)
ageSum := 0.0
for _, r := range records {
    ageSum += float(r.Age)
    fmt.Printf("Name: %s Age: %d\n", r.Name, r.Age)
}
fmt.Println("Average age:%f", ageSum/10.0)
```

**Comment by roll** [comment]
@danielfireman 
I'm also +1 for JSON-like. My comment about SQL-like was more like it could be better to use some proven solution and JSON-like seems even better. I've read how it works and flexibility with supporting both declared interface or empty interface {} should be good fit for Frictionless Data eco-system where people do many researches etc (e.g. quickly read and print data without full type declaration). I suppose it's not a point of this example but just as a note `records -> rows`, `Table.Read` etc as a part of naming consistency (where possible) between implementations.

**Comment by danielfireman** [comment]
Got it.

I will keep in mind the naming consistency. Thanks for the heads up!
