### ISSUE TITLE
Support remote schema descriptor

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-go#35]
# Overview

There is:

```go
schema.ReadFromFile("schema.json")
```

Not sure is there a counterpart for remote schema.

**Comment by danielfireman** [comment]
No. Not yet.

I was targeting the [basic implementation](https://github.com/frictionlessdata/implementations#interface), as described in the [design document](https://docs.google.com/document/d/1aw8SR9S6KbfljUjk7CB72lCGNv3cOYMCAY5KXaOUSVU/edit?usp=sharing)

**Comment by roll** [comment]
@danielfireman 
Cool. I've updated it to be an enhancement. It seems we miss it in requirements but all basic implementations support it.
