### ISSUE TITLE
More detailed readme

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-go#36]
# Overview

For now the readme is useful but still lacks more detailed information on `Table/Schema/Field` APIs. What exact methods/functions are supported etc. See https://github.com/frictionlessdata/tableschema-js#documentation

**Comment by danielfireman** [comment]
I am using [Godoc](https://godoc.org/github.com/frictionlessdata/tableschema-go) for that

There is a godoc badge in the Readme

It is automatically updated based on the code comments.

**Comment by roll** [comment]
@danielfireman 
Thanks. Missed that. May be we could add the godoc note/link also to `documentation` section.
