### ISSUE TITLE
Support bareNumber option for integer and number types

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-go#37]
# Overview

See http://specs.frictionlessdata.io/table-schema/#number. Also we should update current behavior on currencies etc.

**Comment by danielfireman** [comment]
Just to be entirely clear: what exactly do you mean by "update current behavior on currencies etc"?

**Comment by danielfireman** [comment]
All done. Thanks for catching this missing feature! Leaving the issue opened until we clarify the description.

**Comment by roll** [comment]
@danielfireman 
There was a change in specs that replaces `number.currency` by `number.bareNumber`. E.g. for JavaScript  it leads to - https://github.com/frictionlessdata/tableschema-js/commit/8c399e25de98cf3463c54879e1afd79e78a7d684

**Comment by danielfireman** [comment]
Cool. That is exactly how I implemented it (followed the specs). Thanks for the heads up!

Marking this issue as finished.

**Comment by roll** [comment]
:+1:
