### ISSUE TITLE
Implement "unique" constraint and other constraints?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-go#42]
# Overview

Unique constraint e.g. in Python when we iterating table rows - https://github.com/frictionlessdata/tableschema-py/blob/master/tableschema/table.py#L94-L104

Also to be sure we support all list of constraints:
- [x] required
- [ ] unique
- [ ] minLength
- [ ] maxLength
- [ ] minimum
- [ ] maximum
- [ ] enum

**Comment by danielfireman** [comment]
Great catch. The current version of tableshema-go is not supporting constraints.

**Comment by danielfireman** [comment]
Opened issues for specific implementations. It is easier to track and get contributions.
