### ISSUE TITLE
Implement `date` field constraints

### ISSUE THREAD

**Issue by danielfireman** [frictionlessdata/tableschema-go#44]
According to [tableschema specs](https://specs.frictionlessdata.io/table-schema/#constraints), `date` fields could have two constraints associated to it: maximum and minimum.

A similar implementation (for yearMonth fields), can be found at e86d9a7

**Comment by cored** [comment]
@danielfireman would like to try to add this feature.

**Comment by danielfireman** [comment]
Nice! Go for it, @cored !

**Comment by danielfireman** [comment]
Super cool stuff! Thanks for your contribution, @cored!
