### ISSUE TITLE
Implement `string` type constraints

### ISSUE THREAD

**Issue by danielfireman** [frictionlessdata/tableschema-go#46]
According to [tableschema specs](https://specs.frictionlessdata.io/table-schema/#constraints), `string` fields could have many constraints associated to it: pattern, minLength, maxLength

A similar implementation (for yearMonth fields), can be found at e86d9a7

**Comment by hwchiu** [comment]
Hi @danielfireman.
I would like to try to solve this problem. According to tableschema specs, should I add a new filed `pattern` to `Constraints  struct` in `schema/field.go`?
And, for the **string** constraints, The string should match those pattern and its length should between minLength and MaxLength, Do I have any missing ?

Thanks.

**Comment by danielfireman** [comment]
Hi @hwchiu , good morning!

> According to tableschema specs, should I add three new fileds pattern , minLenght and maxLength to Constraints struct in schema/field.go?

Yes, exactly.

> The string should match those pattern and its length should between minLength and MaxLength, Do I have any missing ?

No. I believe that's it.

Could you please split the completion of this issue into more than one PR? For instance, one PR adding the maxLength, other adding the pattern and so on. That would definitely speed up the review process.

Thanks!

**Comment by hwchiu** [comment]
Hi @danielfireman , good evening! (:D)
Thanks your reply.

I will write those modification tomorrow morning and send PRs after I have finish it .
By the way, I should also modify all existing castString function to support a constraint, right ?

**Comment by danielfireman** [comment]
You're very welcome!

> I will write those modification tomorrow morning and send PRs after I have finish it .

Sounds great.

> By the way, I should also modify all existing castString function to support a constraint, right ?

There is only one (unexporeted) castString function and that is called by infer.go and field.go.

Could you please enjoy and rename it to decodeString?

**Comment by hwchiu** [comment]
Thanks your help. Are there anything that I can help about this issue ?

**Comment by danielfireman** [comment]
Thank you! I believe this is it for this particular issue. Closing it out.
