### ISSUE TITLE
Implement unique constraint

### ISSUE THREAD

**Issue by danielfireman** [frictionlessdata/tableschema-go#47]
This constraint can be used in all types:

>  If true, then all values for that field MUST be unique within the data file in which it is found.

In tableschema Go's implementation, it only makes sense to have unique constraint checked during schema.DecodeTable.

**Comment by ajurasz** [comment]
Hi, @danielfireman  I would like to give it a try. So far I was reviewing codebase and I think I know how to achieve the main goal, but will know more when I will fork this repository and start coding ;)

**Comment by danielfireman** [comment]
Great stuff, @ajurasz! Please let us know if you have questions or run into any problems.

One question that has just crossed my mind: should we check uniqueness based on the raw version of the field or the decoded version? For instance, "10,10" and "[10,10]" are different strings but they represent the same geopoint. The former is definitely more performant, but the latter seems more accurate.

@roll , @akariv  could you please shed some light here? Unfortunately, I could not fully grasp the python and JS implementations.

**Comment by roll** [comment]
@danielfireman 
Constraints is a post-cast concept. So for all constraints we have a deal with a [logical representation](http://specs.frictionlessdata.io/table-schema/#physical-and-logical-representation). And it's true that `unique` only one constraint that applies on a `Table` level - http://specs.frictionlessdata.io/table-schema/#physical-and-logical-representation

**Comment by danielfireman** [comment]
Thanks, @ajurasz !
