### ISSUE TITLE
Add Table Iterator

### ISSUE THREAD

**Issue by danielfireman** [frictionlessdata/tableschema-go#5]
Even though this is blocked by #3, lets explicit the possible ways to go. The proposals are inspired by [mgo#Iter ](https://godoc.org/gopkg.in/mgo.v2#Iter), [AWS DynamoDB](https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/) and [database/sql](https://golang.org/pkg/database/sql/).

We are going to follow [good practices](https://blog.golang.org/context) and context object will be part of the API. This might allow setting things like timeouts or early termination if the outer context is Done.

Having the struct describing the row would allow us to have fragments like:

```go
var results []people.Person
if err := table.All(ctx, &results); err != nil {
    return err
}
for i,p := range results {
    fmt.Printf("%d - %+v", i, p)
}
```

Which loads all table records to memory and ranges over its results. If the table is too big, another option could be used:

```go
var person people.Person
iter := table.Batch(100).Iter()
defer iter.Close()
for iter.Next(ctx, &person) {
    fmt.Printf("%+v", p)
}
if err := iter.Err(); err != nil {
    return err
}
```
---
- Edit: Added context to the more complicated case

**Comment by danielfireman** [comment]
After some thinking and taking a very close look at Ruffus' [issue](https://github.com/frictionlessdata/tableschema-js/issues/78), I would like to propose the following API.

@roll @danfowler Could you please take a look? It is important to bear in mind that Go is statically typed.

```go
// RawIter iterates over a set of rows in its raw form.
type RawIter struct {
}

// Next retrieves the next row from the table, blocking if necessary.
// The row is returned in its raw form, as a slice of strings.
func (i *RawIter) Next() ([]string, error) {
	return nil, nil
}

// Done returns true only if a follow up Next call is guaranteed to return false.
func (i *RawIter) Done() bool {
	return false
}

// RowIter iterates over a set of rows in a table, casting its rows to a
// specified schema.
type RowIter struct {
	Schema schema.Schema
}

// Next retrieves the next row from the table, blocking if necessary.
// The row is returned as a struct, cast to using the Schema.
// See: http://godoc.org/github.com/frictionlessdata/tableschema-go/schema#Schema.CastRow
func (i *RowIter) Next(out interface{}) error {
	return nil
}

// Table represents a tabular data structure. Tabular data consists of a set of rows.
// Each row has a set of fields (columns). We usually expect that each row has
// the same set of fields and thus we can talk about the fields for the table as a whole.
// More at: https://specs.frictionlessdata.io/table-schema/#concepts
type Table struct {
}

// Raw allows to iterate over the table in its raw form (values as strings).
// No validation or cast is performed.
func (t *Table) Raw() (*RawIter, error) {
	return nil, nil
}

// Row allows to iterate over the table casting its rows to the passed-in
// schema.
func (t *Table) Row(schema schema.Schema) (*RowIter, error) {
	return nil, nil
}

// CSV creates a Table from the CSV physical representation.
func CSV(source io.Reader) (*Table, error) {
	return nil, nil
}

// JSON creates a Table from the JSON physical representation.
func JSON(source io.Reader) (*Table, error) {
	return nil, nil
}
```

**Comment by roll** [comment]
@danielfireman 
What I've got lately for JavaScript based on the same issue - https://github.com/frictionlessdata/tableschema-js/tree/table-fix#table

Related to static typed implementation.. I think you idea of replacing `iter/read` is good but I have a concern about `table.Raw/Rows()` naming. I would say `Raw` sound more like bytes. May be more explicit like `table.Rows()/CastRows()`?
