### ISSUE TITLE
Refactor datetime.go file

### ISSUE THREAD

**Issue by as27** [frictionlessdata/tableschema-go#54]
Inside [datetime.go](https://github.com/frictionlessdata/tableschema-go/blob/master/schema/datetime.go#L47) in a case of an error the functions returns time.Now()

```Go
func decodeYearMonth(value string, c Constraints) (time.Time, error) {
	y, err := decodeYearMonthWithoutChecks(value)
	if err != nil {
		return time.Now(), err
	}
```
This could cause a bug, when the caller of the function does not check the returned error.  I would suggest to change the return value to an empty time.Time 

```
return time.Time{}, err
```

**Comment by danielfireman** [comment]
Great catch, @as27!

**Comment by as27** [comment]
I will fix this.
