### ISSUE TITLE
Version 1.11 seems to have been released by mistake

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-go#81]
# Overview

Hi @danielfireman, I've added the release version of this package to our status page - https://github.com/frictionlessdata/software/blob/master/STATUS.md and it seems that by semver the latest version is `1.11` which is not really the last one

Probably we can just release `1.12` to solve it without breaking things.

WDYT?

**Comment by danielfireman** [comment]
Cool. I didn't know there is a way to calculate/infer the correct semver label. Which software are you using?

About releasing a new 1.12 version, I think it was simples and would work, but after some more reading, I opted for finally fixing the release labels and making 1.2 the latest stable (much smaller than 1.12).

Checked the status page and looks ok, could you please doublecheck?

**Comment by roll** [comment]
@danielfireman 
Hi, not sure I understand - you mean how we choose which version to release? Just basic semver - https://github.com/frictionlessdata/software#labels (major/minor/fix). And comparision happens like this `major1 > major2, minor1 > minor2, fix1 > fix2`

It shows now `1.2` as the latest version. Which I guess correct. Although still a little bit confusing, for example, regarding the `1.4` tag or the most recent `1.1.1` version.

**Comment by danielfireman** [comment]
Sorry about the confusion. The summary is that I decided to enjoy the beginning of the project to make the whole release history saner, which led to `1.2` instead of `1.12`. Now we can evolve from a cleaner slate.

You right, the latest stable version is `1.2` and I believe this solves the problem. Thanks for pointing this out!
