### ISSUE TITLE
Error trying to CastTable.

### ISSUE THREAD

**Issue by joeberth** [frictionlessdata/tableschema-go#83]
# Overview

Error when using the csv [employee](https://github.com/frictionlessdata/tableschema-go/files/5111794/employee.xlsx), the 
[schema](https://github.com/frictionlessdata/tableschema-go/files/5111828/schema.txt) and trying to use the function [CastTable(tab table.Table, out interface{})](https://github.com/frictionlessdata/tableschema-go/blob/72210a2e206a8a6fbfd35a1979499a2ba5d078e1/schema/schema.go#L349 ). References the out argument of this function to this  [struct](https://github.com/frictionlessdata/tableschema-go/files/5111829/struct.txt)

Using this function produces following error:
"strconv.ParseInt: parsing " 2020": invalid syntax"

Which is strange, because when adding the test case directly to the [integer_test.go](https://github.com/frictionlessdata/tableschema-go/blob/master/schema/integer_test.go)  of the tableschema-go, it does not produce an error.

This error is fixed when i delete white spaces before call CastTable.

---
@danielfireman

**Comment by danielfireman** [comment]
HI @joeberth, thanks for reporting!

The library behavior is correct. If you would like to strip the prefixed whitespaces you need to set `bareNumber: false` in the schema field. The behavior is documented [here](https://specs.frictionlessdata.io/table-schema/#types-and-formats) and implemented [here](https://github.com/frictionlessdata/tableschema-go/blob/master/schema/integer.go#L13).
