### ISSUE TITLE
Support GZIP compressed CSV files

### ISSUE THREAD

**Issue by cuducos** [frictionlessdata/tableschema-go#94]
# Overview

In many projects, I work we store compressed CSV (e.g. `mydata.csv.gz`) instead of plain CSV (e.g. `mydata.csv`).

Is it interesting for this project to allow `csv.FromFile` to support _gzipped_ CSV files? If so, I'd be more than happy to implement this feature.

## Intended roadmap

1. We can use [`filepath.Ext`](https://golang.org/pkg/path/filepath/#Ext) to check whether `path` has `.gz` or `.gzip` as extension [when we generate the `csv.Source`](https://github.com/frictionlessdata/tableschema-go/blob/master/csv/table.go#L181);
2. Then, if that's the case, we use Go's native `compress/gzip` lib to return a [`gzip.Reader`](https://golang.org/pkg/compress/gzip/#Reader);
3. A `gzip.Reader` matches `io.ReadCloser` interface, satisfying `csv.Source`. 

What do you think?
---

Please preserve this line to notify @danielfireman (lead of this repository)

**Comment by danielfireman** [comment]
I believe this is a great idea. Unfortunately I won't be able to get to this in a month or so.
